language: cpp

dist: trusty
sudo: required

before_script:
  - base_dir=$PWD && mkdir travis_deps && cd travis_deps
  - sudo apt-get update -qq
  - git clone https://github.com/google/googletest.git gtest
  - mkdir -p gtest/build && cd gtest/build && cmake ../ && make && sudo make install
  - cd ${base_dir}

matrix:
  include:
    - os: linux
      env: CXX=g++-4.9 CC=gcc-4.8
      addons:
        apt:
          packages:
            - g++-4.9
            - libstdc++6
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - libstdc++6
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
            - libstdc++6
          sources: &sources
            - ubuntu-toolchain-r-test
    - os: linux
      env: CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          sources: *sources
          packages:
            - clang-3.6
            - libstdc++6
    - os: linux
      env: CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          sources: *sources
          packages:
            - clang-3.7
            - libstdc++6
    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources: *sources
          packages:
            - clang-3.8
            - libstdc++6

script:
  - uname -a
  - $CXX --version
  - mkdir build
  - cd build
  - cmake .. && make && make test